"""Initial again

Revision ID: 08e51d6ec5d0
Revises: 
Create Date: 2025-05-16 11:21:03.516706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e51d6ec5d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articul', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vid', sa.String(), nullable=True),
    sa.Column('brend', sa.String(), nullable=True),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('ostatok', sa.String(), nullable=True),
    sa.Column('sklad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse_stock')
    # ### end Alembic commands ###
