"""add updated_at to warehouse_stock

Revision ID: 1fe679cd3fc0
Revises: 63dfa915c283
Create Date: 2025-05-21 10:35:19.688091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe679cd3fc0'
down_revision: Union[str, None] = '63dfa915c283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. nullable=True временно
    op.add_column('warehouse_stock', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # 2. Заполняем текущей датой
    op.execute("UPDATE warehouse_stock SET updated_at = now()")

    # 3. Теперь добавим ограничение NOT NULL
    op.alter_column('warehouse_stock', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_stock', 'updated_at')
    # ### end Alembic commands ###
