"""add unique kod+sklad

Revision ID: ca37acfd27d0
Revises: 08e51d6ec5d0
Create Date: 2025-05-16 11:41:48.588659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca37acfd27d0'
down_revision: Union[str, None] = '08e51d6ec5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_kod_sklad', 'warehouse_stock', ['kod', 'sklad'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_kod_sklad', 'warehouse_stock', type_='unique')
    # ### end Alembic commands ###
