"""init schema

Revision ID: d0ea1e276c9b
Revises: 
Create Date: 2025-05-16 16:15:21.307508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ea1e276c9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articul', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vid', sa.String(), nullable=True),
    sa.Column('brend', sa.String(), nullable=True),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('ostatok', sa.String(), nullable=True),
    sa.Column('sklad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod', 'sklad', name='uix_kod_sklad')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse_stock')
    op.drop_table('user_query_log')
    # ### end Alembic commands ###
